version: "3.9"
services:
  web:
    ports:
      - 9138:8000
    image: mobyit/catchemall:${TAG}
    volumes:
      - pokedata:/app/data
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first
volumes:
  pokedata:
    external: true
      